# Generated by Django 3.2.9 on 2021-12-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_auto_20211206_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnos',
            old_name='actividad_realizar',
            new_name='actividad',
        ),
    ]
