# Generated by Django 3.2.9 on 2021-12-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.AddField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatares'),
        ),
    ]
