# Generated by Django 3.2.9 on 2021-12-25 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_usuarios_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.usuarios')),
            ],
        ),
    ]
